---
- name: Install HAProxy
  apt:
    name: haproxy
    state: latest
    update_cache: yes

- name: Copy HAProxy configuration
  template:
    src: haproxy.cfg
    dest: /etc/haproxy/haproxy.cfg
  notify: Restart HAProxy

- name: Ensure HAProxy is running and enabled
  systemd:
    name: haproxy
    state: started
    enabled: yes
