---
- name: Install Nginx
  apt:
    name: nginx
    state: latest
    update_cache: yes

- name: Copy Nginx configuration
  template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
  notify: Restart Nginx

- name: Ensure Nginx is running and enabled
  systemd:
    name: nginx
    state: started
    enabled: yes